// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgtsaxcgDPaB_MIsNt4VmZayt67oczI5A',
    appId: '1:339592140112:web:14a3739c8ae73a9bcd0855',
    messagingSenderId: '339592140112',
    projectId: 'shopflow-1d1e1',
    authDomain: 'shopflow-1d1e1.firebaseapp.com',
    storageBucket: 'shopflow-1d1e1.firebasestorage.app',
    measurementId: 'G-MN21WGK62B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD4X3NaYoCn1dywznYq1a-Qe8ep2gBcQQ',
    appId: '1:339592140112:android:7eab6198e18a1f05cd0855',
    messagingSenderId: '339592140112',
    projectId: 'shopflow-1d1e1',
    storageBucket: 'shopflow-1d1e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0VXRF38WhsXJDNUyHS09K4I36MMjh1k',
    appId: '1:339592140112:ios:fed85a0741c806dacd0855',
    messagingSenderId: '339592140112',
    projectId: 'shopflow-1d1e1',
    storageBucket: 'shopflow-1d1e1.firebasestorage.app',
    iosClientId: '339592140112-33mcrq61flcspm814nn0j196h4fbi227.apps.googleusercontent.com',
    iosBundleId: 'com.app.shopflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0VXRF38WhsXJDNUyHS09K4I36MMjh1k',
    appId: '1:339592140112:ios:fed85a0741c806dacd0855',
    messagingSenderId: '339592140112',
    projectId: 'shopflow-1d1e1',
    storageBucket: 'shopflow-1d1e1.firebasestorage.app',
    iosClientId: '339592140112-33mcrq61flcspm814nn0j196h4fbi227.apps.googleusercontent.com',
    iosBundleId: 'com.app.shopflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgtsaxcgDPaB_MIsNt4VmZayt67oczI5A',
    appId: '1:339592140112:web:5be40b308f29ce8dcd0855',
    messagingSenderId: '339592140112',
    projectId: 'shopflow-1d1e1',
    authDomain: 'shopflow-1d1e1.firebaseapp.com',
    storageBucket: 'shopflow-1d1e1.firebasestorage.app',
    measurementId: 'G-1Y7STMZ0MQ',
  );

}